<?xml version="1.0" encoding="UTF-8" ?>
<Package name="PepperDBinout4" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="pepperSpeech" src="db/pepperSpeech.sqlite" />
        <File name="index" src="html/index.html" />
        <File name="color" src="html/color.html" />
        <File name="Pepper_BG01" src="html/images/Pepper_BG01.png" />
        <File name="color01" src="html/images/color01.png" />
        <File name="interrupt06" src="html/images/interrupt06.png" />
        <File name="normal04" src="html/images/normal04.png" />
        <File name="rule04" src="html/images/rule04.png" />
        <File name="speed03" src="html/images/speed03.png" />
        <File name="start01" src="html/images/start01.png" />
        <File name="tempo100_01" src="html/images/tempo100_01.png" />
        <File name="tempo120_03" src="html/images/tempo120_03.png" />
        <File name="tempo150_02" src="html/images/tempo150_02.png" />
        <File name="tempo200_02" src="html/images/tempo200_02.png" />
        <File name="titleColor" src="html/images/titleColor.png" />
        <File name="titleNormal" src="html/images/titleNormal.png" />
        <File name="titleToppng" src="html/images/titleToppng.png" />
        <File name="top03" src="html/images/top03.png" />
        <File name="main" src="html/main.css" />
        <File name="main" src="html/main.js" />
        <File name="normal" src="html/normal.html" />
        <File name="__init__" src="lib/gevent/__init__.py" />
        <File name="__init__" src="lib/gevent/__init__.pyc" />
        <File name="_corecffi_build" src="lib/gevent/_corecffi_build.py" />
        <File name="_corecffi_build" src="lib/gevent/_corecffi_build.pyc" />
        <File name="_fileobjectcommon" src="lib/gevent/_fileobjectcommon.py" />
        <File name="_fileobjectcommon" src="lib/gevent/_fileobjectcommon.pyc" />
        <File name="_fileobjectposix" src="lib/gevent/_fileobjectposix.py" />
        <File name="_fileobjectposix" src="lib/gevent/_fileobjectposix.pyc" />
        <File name="_semaphore" src="lib/gevent/_semaphore.py" />
        <File name="_semaphore" src="lib/gevent/_semaphore.pyc" />
        <File name="_semaphore" src="lib/gevent/_semaphore.pyd" />
        <File name="_socket2" src="lib/gevent/_socket2.py" />
        <File name="_socket2" src="lib/gevent/_socket2.pyc" />
        <File name="_socketcommon" src="lib/gevent/_socketcommon.py" />
        <File name="_socketcommon" src="lib/gevent/_socketcommon.pyc" />
        <File name="_ssl2" src="lib/gevent/_ssl2.py" />
        <File name="_ssl2" src="lib/gevent/_ssl2.pyc" />
        <File name="_ssl3" src="lib/gevent/_ssl3.py" />
        <File name="_ssl3" src="lib/gevent/_ssl3.pyc" />
        <File name="_sslgte279" src="lib/gevent/_sslgte279.py" />
        <File name="_sslgte279" src="lib/gevent/_sslgte279.pyc" />
        <File name="_tblib" src="lib/gevent/_tblib.py" />
        <File name="_tblib" src="lib/gevent/_tblib.pyc" />
        <File name="_threading" src="lib/gevent/_threading.py" />
        <File name="_threading" src="lib/gevent/_threading.pyc" />
        <File name="_util_py2" src="lib/gevent/_util_py2.py" />
        <File name="_util_py2" src="lib/gevent/_util_py2.pyc" />
        <File name="ares" src="lib/gevent/ares.pyd" />
        <File name="backdoor" src="lib/gevent/backdoor.py" />
        <File name="backdoor" src="lib/gevent/backdoor.pyc" />
        <File name="baseserver" src="lib/gevent/baseserver.py" />
        <File name="baseserver" src="lib/gevent/baseserver.pyc" />
        <File name="builtins" src="lib/gevent/builtins.py" />
        <File name="builtins" src="lib/gevent/builtins.pyc" />
        <File name="core" src="lib/gevent/core.py" />
        <File name="core" src="lib/gevent/core.pyc" />
        <File name="corecext" src="lib/gevent/corecext.pyd" />
        <File name="corecffi" src="lib/gevent/corecffi.py" />
        <File name="corecffi" src="lib/gevent/corecffi.pyc" />
        <File name="coros" src="lib/gevent/coros.py" />
        <File name="coros" src="lib/gevent/coros.pyc" />
        <File name="event" src="lib/gevent/event.py" />
        <File name="event" src="lib/gevent/event.pyc" />
        <File name="fileobject" src="lib/gevent/fileobject.py" />
        <File name="fileobject" src="lib/gevent/fileobject.pyc" />
        <File name="greenlet" src="lib/gevent/greenlet.py" />
        <File name="greenlet" src="lib/gevent/greenlet.pyc" />
        <File name="hub" src="lib/gevent/hub.py" />
        <File name="hub" src="lib/gevent/hub.pyc" />
        <File name="local" src="lib/gevent/local.py" />
        <File name="local" src="lib/gevent/local.pyc" />
        <File name="lock" src="lib/gevent/lock.py" />
        <File name="lock" src="lib/gevent/lock.pyc" />
        <File name="monkey" src="lib/gevent/monkey.py" />
        <File name="monkey" src="lib/gevent/monkey.pyc" />
        <File name="os" src="lib/gevent/os.py" />
        <File name="os" src="lib/gevent/os.pyc" />
        <File name="pool" src="lib/gevent/pool.py" />
        <File name="pool" src="lib/gevent/pool.pyc" />
        <File name="pywsgi" src="lib/gevent/pywsgi.py" />
        <File name="pywsgi" src="lib/gevent/pywsgi.pyc" />
        <File name="queue" src="lib/gevent/queue.py" />
        <File name="queue" src="lib/gevent/queue.pyc" />
        <File name="resolver_ares" src="lib/gevent/resolver_ares.py" />
        <File name="resolver_ares" src="lib/gevent/resolver_ares.pyc" />
        <File name="resolver_thread" src="lib/gevent/resolver_thread.py" />
        <File name="resolver_thread" src="lib/gevent/resolver_thread.pyc" />
        <File name="select" src="lib/gevent/select.py" />
        <File name="select" src="lib/gevent/select.pyc" />
        <File name="server" src="lib/gevent/server.py" />
        <File name="server" src="lib/gevent/server.pyc" />
        <File name="signal" src="lib/gevent/signal.py" />
        <File name="signal" src="lib/gevent/signal.pyc" />
        <File name="socket" src="lib/gevent/socket.py" />
        <File name="socket" src="lib/gevent/socket.pyc" />
        <File name="ssl" src="lib/gevent/ssl.py" />
        <File name="ssl" src="lib/gevent/ssl.pyc" />
        <File name="subprocess" src="lib/gevent/subprocess.py" />
        <File name="subprocess" src="lib/gevent/subprocess.pyc" />
        <File name="thread" src="lib/gevent/thread.py" />
        <File name="thread" src="lib/gevent/thread.pyc" />
        <File name="threading" src="lib/gevent/threading.py" />
        <File name="threading" src="lib/gevent/threading.pyc" />
        <File name="threadpool" src="lib/gevent/threadpool.py" />
        <File name="threadpool" src="lib/gevent/threadpool.pyc" />
        <File name="timeout" src="lib/gevent/timeout.py" />
        <File name="timeout" src="lib/gevent/timeout.pyc" />
        <File name="util" src="lib/gevent/util.py" />
        <File name="util" src="lib/gevent/util.pyc" />
        <File name="win32util" src="lib/gevent/win32util.py" />
        <File name="win32util" src="lib/gevent/win32util.pyc" />
        <File name="wsgi" src="lib/gevent/wsgi.py" />
        <File name="wsgi" src="lib/gevent/wsgi.pyc" />
        <File name="greenlet" src="lib/greenlet.pyd" />
        <File name="six" src="lib/six.py" />
        <File name="six" src="lib/six.pyc" />
        <File name="__init__" src="lib/websocket/__init__.py" />
        <File name="__init__" src="lib/websocket/__init__.pyc" />
        <File name="_abnf" src="lib/websocket/_abnf.py" />
        <File name="_abnf" src="lib/websocket/_abnf.pyc" />
        <File name="_app" src="lib/websocket/_app.py" />
        <File name="_app" src="lib/websocket/_app.pyc" />
        <File name="_core" src="lib/websocket/_core.py" />
        <File name="_core" src="lib/websocket/_core.pyc" />
        <File name="_exceptions" src="lib/websocket/_exceptions.py" />
        <File name="_exceptions" src="lib/websocket/_exceptions.pyc" />
        <File name="_handshake" src="lib/websocket/_handshake.py" />
        <File name="_handshake" src="lib/websocket/_handshake.pyc" />
        <File name="_http" src="lib/websocket/_http.py" />
        <File name="_http" src="lib/websocket/_http.pyc" />
        <File name="_logging" src="lib/websocket/_logging.py" />
        <File name="_logging" src="lib/websocket/_logging.pyc" />
        <File name="_socket" src="lib/websocket/_socket.py" />
        <File name="_socket" src="lib/websocket/_socket.pyc" />
        <File name="_ssl_compat" src="lib/websocket/_ssl_compat.py" />
        <File name="_ssl_compat" src="lib/websocket/_ssl_compat.pyc" />
        <File name="_url" src="lib/websocket/_url.py" />
        <File name="_url" src="lib/websocket/_url.pyc" />
        <File name="_utils" src="lib/websocket/_utils.py" />
        <File name="_utils" src="lib/websocket/_utils.pyc" />
        <File name="cacert" src="lib/websocket/cacert.pem" />
        <File name="WebSocketMain" src="lib/websocket/data/WebSocketMain.swf" />
        <File name="__init__" src="lib/websocket/data/__init__.py" />
        <File name="__init__" src="lib/websocket/data/__init__.pyc" />
        <File name="flashsocket" src="lib/websocket/data/flashsocket.js" />
        <File name="policyserver" src="lib/websocket/policyserver.py" />
        <File name="policyserver" src="lib/websocket/policyserver.pyc" />
        <File name="server" src="lib/websocket/server.py" />
        <File name="server" src="lib/websocket/server.pyc" />
        <File name="__init__" src="lib/websocket/tests/__init__.py" />
        <File name="__init__" src="lib/websocket/tests/__init__.pyc" />
        <File name="header01" src="lib/websocket/tests/data/header01.txt" />
        <File name="header02" src="lib/websocket/tests/data/header02.txt" />
        <File name="test_websocket" src="lib/websocket/tests/test_websocket.py" />
        <File name="test_websocket" src="lib/websocket/tests/test_websocket.pyc" />
    </Resources>
    <Topics />
    <IgnoredPaths>
        <Path src=".metadata" />
    </IgnoredPaths>
</Package>
